# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kahne Raja. Coder. Web Specialist. Scrum Master. Blogger. Speaker. Artist. Musician."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kahneraja.com" # the base hostname & protocol for your site
permalink: /:title/
encoding: utf-8
# Build settings
markdown: kramdown